import path from "node:path";
import fs from "node:fs/promises";
import { log, ensureDir, slug, ts, sleep } from "./util.js";

// Throttle between sequential gpt-image-1 calls to stay under per-minute rate limits.
const IMAGE_THROTTLE_MS = 2000;
import { generateCopy } from "./task-agents/copy.js";
import { generateHero } from "./task-agents/image.js";
import { reviewCopy } from "./task-agents/review.js";
import { buildHtml, writeHtml } from "./tools/html.js";
import { htmlToImage } from "./tools/render.js";

/**
 * Run a full campaign generation: per-product copy, then per-(product, ratio)
 * hero + HTML + PNG. Heroes can come from local files (per-product or
 * company-wide) or be generated by gpt-image-1.
 *
 * @param {object} args
 * @param {object} args.brief     Validated brief.
 * @param {string} args.briefPath Absolute path to the brief file; used to
 *                                resolve relative asset paths inside the brief.
 * @param {string[]} args.ratios  e.g. ["1:1","16:9","9:16"]
 * @param {string} args.outDir    Where the run folder is created.
 */
export async function runCampaign({ brief, briefPath, ratios, outDir }) {
  const briefDir = path.dirname(briefPath);
  const stamp = `${slug(brief.campaign)}-${ts()}`;
  const runDir = path.join(outDir, stamp);
  await ensureDir(runDir);

  const logoAbsPath = brief.brand.logo_path
    ? path.resolve(briefDir, brief.brand.logo_path)
    : null;
  if (logoAbsPath) {
    try {
      await fs.access(logoAbsPath);
    } catch {
      log.warn(`Logo not found at ${logoAbsPath}; rendering without logo.`);
    }
  }

  // Pre-compute product slugs (used both for output dirs and for asset lookups).
  const productSlugs = brief.products.map((p) => ({
    product: p,
    productSlug: slug(p.name),
  }));

  const pathExists = async (p) => {
    try { await fs.access(p); return true; } catch { return false; }
  };

  // Hero image resolution per (product, ratio). Precedence:
  //   1. assets/{productSlug}/hero-{ratio-tag}.png  (product-specific)
  //   2. assets/company/hero-{ratio-tag}.png        (campaign-wide)
  //   3. brief.hero.image                           (single brief-level fallback)
  //   4. gpt-image-1
  let globalUserHeroPath = brief.hero.image
    ? path.resolve(briefDir, brief.hero.image)
    : null;
  if (globalUserHeroPath && !(await pathExists(globalUserHeroPath))) {
    log.warn(`Hero image not found at ${globalUserHeroPath}; falling back to other sources.`);
    globalUserHeroPath = null;
  }

  const companyHeros = {};
  for (const ratio of ratios) {
    const tag = ratio.replace(":", "x");
    const candidate = path.resolve(briefDir, "assets", "company", `hero-${tag}.png`);
    if (await pathExists(candidate)) {
      companyHeros[ratio] = candidate;
      log.info(`Using company hero for ${ratio}: ${path.relative(process.cwd(), candidate)}`);
    } else {
      companyHeros[ratio] = null;
    }
  }

  const productHeros = {};
  for (const { product, productSlug } of productSlugs) {
    productHeros[productSlug] = {};
    for (const ratio of ratios) {
      const tag = ratio.replace(":", "x");
      const candidate = path.resolve(briefDir, "assets", productSlug, `hero-${tag}.png`);
      if (await pathExists(candidate)) {
        productHeros[productSlug][ratio] = candidate;
        log.info(`Using product hero for [${product.name}][${ratio}]: ${path.relative(process.cwd(), candidate)}`);
      } else {
        productHeros[productSlug][ratio] = null;
      }
    }
  }

  const resolveHero = (productSlug, ratio) =>
    productHeros[productSlug][ratio] ?? companyHeros[ratio] ?? globalUserHeroPath;

  // Phase 1: per-product copy (one gpt-4o-mini call per product).
  log.info(`Generating copy for ${brief.products.length} products (gpt-4o-mini)...`);
  const productEntries = [];
  for (const { product, productSlug } of productSlugs) {
    const productDir = path.join(runDir, "products", productSlug);
    const imagesDir = path.join(productDir, "images");
    await ensureDir(imagesDir);

    log.info(`  [${product.name}] copy...`);
    const copy = await generateCopy(brief, product);
    await fs.writeFile(
      path.join(productDir, "copy.json"),
      JSON.stringify(copy, null, 2),
    );
    const postText =
      `${copy.post.caption}\n\n` +
      copy.post.hashtags.map((h) => `#${h}`).join(" ");
    await fs.writeFile(path.join(productDir, "post.txt"), postText, "utf8");

    productEntries.push({ product, productSlug, productDir, imagesDir, copy });
  }
  log.ok(`Copy ready for ${productEntries.length} products.`);

  // Phase 1.5: review copy against brand guidelines. Cheap (one gpt-4o-mini
  // call) and runs sync so the user sees feedback before image generation
  // starts the long wait.
  log.info("Reviewing copy against brand guidelines (gpt-4o-mini)...");
  const productCopies = productEntries.map((e) => ({
    product: e.product,
    productSlug: e.productSlug,
    copy: e.copy,
  }));
  const review = await reviewCopy({ brief, productCopies });

  if (review.skipped) {
    log.info(`  Skipped: ${review.reason}`);
  } else {
    await fs.writeFile(
      path.join(runDir, "review.json"),
      JSON.stringify(review, null, 2),
    );
    log.ok(`Review complete: overall ${review.overall_score}/100`);
    if (review.summary) log.info(`  ${review.summary}`);
    for (const p of review.products) {
      const cs = p.contradictions ?? [];
      if (cs.length) {
        log.warn(`  [${p.product}] score ${p.score}/100 — ${cs.length} contradiction(s):`);
        for (const c of cs) {
          log.warn(`    "${c.quote}" violates ${c.violates}`);
        }
      }
    }
    if (review.brief_suggestions?.length) {
      log.info(`  Brief tightening ideas: ${review.brief_suggestions.length}`);
    }
  }

  // Phase 2: per-(product, ratio) hero + HTML + render. One global throttle
  // applies between every pair of image calls so we stay under rate limits.
  const jobs = [];
  for (const entry of productEntries) {
    for (const ratio of ratios) jobs.push({ ...entry, ratio });
  }

  const results = [];
  for (let i = 0; i < jobs.length; i++) {
    const { product, productSlug, productDir, imagesDir, copy, ratio } = jobs[i];
    const tag = ratio.replace(":", "x");
    const label = `[${product.name}][${ratio}]`;
    const heroForRatio = resolveHero(productSlug, ratio);

    if (heroForRatio) {
      log.info(`${label} using user-supplied hero (${heroForRatio})...`);
    } else {
      log.info(`${label} generating hero (gpt-image-1)...`);
    }
    const heroPath = path.join(imagesDir, `hero-${tag}.png`);
    await generateHero({ brief, product, ratio, outPath: heroPath, userHeroPath: heroForRatio });

    log.info(`${label} composing HTML...`);
    const html = buildHtml({
      heroAbsPath: path.resolve(heroPath),
      logoAbsPath,
      overlay: copy.overlay,
      brand: brief.brand,
      ratio,
      cta: brief.cta,
    });
    const htmlPath = path.join(productDir, `post-${tag}.html`);
    await writeHtml(html, htmlPath);

    log.info(`${label} rendering PNG (puppeteer)...`);
    const finalPath = path.join(imagesDir, `post-${tag}.png`);
    await htmlToImage({ htmlPath, ratio, outPath: finalPath });

    results.push({
      product: product.name,
      productSlug,
      ratio,
      hero: heroPath,
      html: htmlPath,
      image: finalPath,
    });
    log.ok(`${label} done -> ${finalPath}`);

    // Only throttle when both this job and the next would hit gpt-image-1.
    const nextJob = jobs[i + 1];
    if (nextJob && !heroForRatio && !resolveHero(nextJob.productSlug, nextJob.ratio)) {
      await sleep(IMAGE_THROTTLE_MS);
    }
  }

  const manifest = {
    generatedAt: new Date().toISOString(),
    runDir,
    brief,
    ratios,
    review,
    products: productEntries.map((e) => ({
      name: e.product.name,
      slug: e.productSlug,
      copy: e.copy,
      posts: results
        .filter((r) => r.productSlug === e.productSlug)
        .map((r) => ({ ratio: r.ratio, hero: r.hero, html: r.html, image: r.image })),
    })),
  };
  await fs.writeFile(
    path.join(runDir, "manifest.json"),
    JSON.stringify(manifest, null, 2),
  );
  return manifest;
}
